TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          FacebookProvider:
            provider: 'FLOW3\Facebook\Security\Authentication\Provider\FacebookProvider'
            entryPoint: 'WebRedirect'
            entryPointOptions: 
              uri: 'index'
              
          
